//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caro
{
    using System;
    using System.Collections.Generic;
    
    public partial class playerName1VSplayerName2
    {
        public int Id { get; set; }
        public string PlayerName1 { get; set; }
        public string PlayerName2 { get; set; }
        public Nullable<int> TimeWonP1 { get; set; }
        public Nullable<int> TimeWonP2 { get; set; }
    }
}
